spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.104:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  application:
    admin:
      enabled: true
server:
  port: 8088
  context-path: /sell



